

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/workspace
spring.datasource.username=root
spring.datasource.password=root


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# JWT CONFIGURATION
# ===============================

jwt.secret=my-super-secret-jwt-key-for-ecommerce-project-123456789
jwt.expiration=3600000

#CLOUDINARY_URL=cloudinary://265255396729379:uLXRU79PIi1aBe1LBcogXXhEmgE@dqeds5aqr

cloudinary.cloud-name=heeqryfp
cloudinary.api-key=747842738852716
cloudinary.api-secret=-YWXk5qxX3LFLjt7L0iZlFCfGEA